version: '3'

volumes:
  mysql:

services:
  nginx-www:
    build:
      context: .
      dockerfile: Dockerfile-www.nginx
    environment:
      PHP_FPM_PASS: php-www
    ports:
      - "81:80"
    links:
      - php-www
    volumes:
      - ./:/var/www:ro

  php-www:
    build:
      context: .
      dockerfile: Dockerfile-www.php
    volumes:
      - ./:/var/www
      - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    links:
      - mysql
    environment:
      PHP_XDEBUG_ENABLED: "no"
      PHP_IDE_CONFIG: serverName=game

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: game
      MYSQL_PASSWORD: game
      MYSQL_DATABASE: game
    volumes:
      - mysql:/var/lib/mysql
      - ./:/var/www

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 3000:80
    links:
      - mysql
